/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FaDiscord, FaTwitter } from "react-icons/fa";
import Loader from "~/components/Loader";

interface NavLinkType {
  text: string | JSX.Element;
  link?: string;
}

const NavLink = ({ text, link }: NavLinkType) => {
  return (
    <a href={link} target="_blank" rel="noopener noreferrer">
      <li className="border-[1px] border-white border-opacity-80 bg-white bg-opacity-20 px-4 py-1 text-sm font-bold uppercase text-white hover:bg-opacity-40">
        {text}
      </li>
    </a>
  );
};

const Home: NextPage = () => {
  const navLinks: NavLinkType[] = [
    // { text: "Link 1", link: "https://jikan.so/" },
    // { text: "Link 2" },
    { text: "Whitepaper", link: "https://whitepaper.foxbyte.app/" },
    { text: <FaTwitter size={20} />, link: "https://twitter.com/foxbyteNFT" },
    {
      text: <FaDiscord size={20} />,
      link: "https://discord.com/invite/foxbyte",
    },
  ];

  return (
    <>
      <Head>
        <title>Foxbyte</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel="icon" href="/logo.png" />
      </Head>

      <Loader />

      <main className="flex h-screen flex-col items-center justify-center bg-[url('https://placehold.co/1080x720?text=Image')] bg-cover bg-center bg-no-repeat p-8">
        <div className="h-full w-full border-[1px] border-white border-opacity-80">
          <nav className="flex items-center justify-between gap-4 border-b-[1px] border-white border-opacity-80 px-4">
            <Link
              href="/"
              className="flex items-center justify-center text-2xl font-bold text-white"
            >
              <img src="/logo.png" alt="logo" width={48} height={48} />
              Foxbyte
            </Link>
            <ul className="flex items-center justify-center gap-4">
              {navLinks.map((item, i) => {
                return (
                  <NavLink
                    key={`link-${i}`}
                    text={item.text}
                    link={item.link}
                  />
                );
              })}
            </ul>
          </nav>

          <div className="-mt-16 flex h-full flex-col items-center justify-end text-white">
            <footer className="flex w-full items-center justify-end gap-4 border-t-[1px] border-white border-opacity-80 p-4 text-xs uppercase">
              <p>&copy; 2023 Foxbyte. All rights reserved</p>
            </footer>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
