/* eslint-disable @next/next/no-img-element */
import { motion } from "framer-motion";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FaDiscord, FaTwitter } from "react-icons/fa";
import Loader from "~/components/Loader";

interface NavLinkType {
  text: string | JSX.Element;
  link?: string;
}

const NavLink = ({ text, link }: NavLinkType) => {
  return (
    <a href={link} target="_blank" rel="noopener noreferrer">
      <li className="border-[1px] border-white border-opacity-80 bg-white bg-opacity-20 px-4 py-1 text-sm font-bold uppercase text-white hover:bg-opacity-40">
        {text}
      </li>
    </a>
  );
};

const Home: NextPage = () => {
  const navLinks: NavLinkType[] = [
    // { text: "Link 1", link: "https://jikan.so/" },
    // { text: "Link 2" },
    { text: "Whitepaper", link: "https://whitepaper.foxbyte.app/" },
    { text: <FaTwitter size={20} />, link: "https://twitter.com/foxbyteNFT" },
    {
      text: <FaDiscord size={20} />,
      link: "https://discord.com/invite/foxbyte",
    },
  ];

  return (
    <>
      <Head>
        <title>Foxbyte</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel="icon" href="/logo.png" />
      </Head>

      <Loader />

      <main className="relative flex h-screen w-screen flex-col items-center justify-center overflow-hidden bg-[url('../HOMEPAGE3_Animation_file_3_2.gif')] bg-cover bg-center bg-no-repeat p-8">
        <motion.div
          className="absolute bottom-0 left-0 z-10"
          initial={{
            x: -300,
            opacity: 0,
          }}
          animate={{
            x: 0,
            opacity: 1,
            transition: {
              type: "spring",
              delay: 4,
              duration: 2,
            },
          }}
        >
          <motion.img
            src="https://placehold.co/250x250?text=Floating+Image"
            alt="floating"
            animate={{
              y: [0, -10, 0],
              transition: {
                type: "tween",
                delay: 6,
                duration: 4,
                repeat: Infinity,
              },
            }}
          />
        </motion.div>
        <motion.div
          className="absolute bottom-0 right-0 z-10"
          initial={{
            x: 300,
            opacity: 0,
          }}
          animate={{
            x: 0,
            opacity: 1,
            transition: {
              type: "spring",
              delay: 4,
              duration: 2,
            },
          }}
        >
          <motion.img
            src="https://placehold.co/250x250?text=Floating+Image"
            alt="floating"
            animate={{
              y: [0, -15, 0],
              transition: {
                type: "tween",
                delay: 6,
                duration: 5,
                repeat: Infinity,
              },
            }}
          />
        </motion.div>

        <div className="z-20 flex h-full w-full flex-col border-[1px] border-white border-opacity-80">
          <nav className="flex items-center justify-between gap-4 border-b-[1px] border-white border-opacity-80 px-4">
            <Link
              href="/"
              className="flex items-center justify-center text-2xl font-bold text-white"
            >
              <img src="/logo.png" alt="logo" width={48} height={48} />
              Foxbyte
            </Link>
            <ul className="flex items-center justify-center gap-4">
              {navLinks.map((item, i) => {
                return (
                  <NavLink
                    key={`link-${i}`}
                    text={item.text}
                    link={item.link}
                  />
                );
              })}
            </ul>
          </nav>

          <div className="h-full"></div>

          <div className="flex flex-col items-center justify-end text-white">
            <footer className="flex w-full items-center justify-end gap-4 border-t-[1px] border-white border-opacity-80 p-4 text-xs uppercase">
              <p>&copy; 2023 Foxbyte. All rights reserved</p>
            </footer>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
